mybatis_config_file: mybatis-config.xml
mapper_path: /mapper/*Mapper.xml
entity_package: org.kwin.management.entity

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/management?useUnicode=true&characterEncoding=utf-8&useSSL=false
  username: root
  password: 123456